set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]
#set_property IOSTANDARD LVCMOS33 [get_ports locked_on]
set_property PACKAGE_PIN N18 [get_ports {BLUE[0]}]
set_property PACKAGE_PIN L18 [get_ports {BLUE[1]}]
set_property PACKAGE_PIN K18 [get_ports {BLUE[2]}]
set_property PACKAGE_PIN J18 [get_ports {BLUE[3]}]
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]
set_property PACKAGE_PIN J17 [get_ports {GREEN[0]}]
set_property PACKAGE_PIN H17 [get_ports {GREEN[1]}]
set_property PACKAGE_PIN G17 [get_ports {GREEN[2]}]
set_property PACKAGE_PIN D17 [get_ports {GREEN[3]}]
set_property PACKAGE_PIN P19 [get_ports HSYNC]
set_property PACKAGE_PIN G19 [get_ports {RED[0]}]
set_property PACKAGE_PIN H19 [get_ports {RED[1]}]
set_property PACKAGE_PIN J19 [get_ports {RED[2]}]
set_property PACKAGE_PIN N19 [get_ports {RED[3]}]
set_property PACKAGE_PIN R19 [get_ports VSYNC]
set_property PACKAGE_PIN U18 [get_ports reset]      
#set_property PACKAGE_PIN U16 [get_ports locked_on]

set_property IOSTANDARD LVCMOS33 [get_ports btn_in]
set_property PACKAGE_PIN W19 [get_ports btn_in]

set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property PACKAGE_PIN V19 [get_ports LED]

# an select pins
set_property PACKAGE_PIN U2 [get_ports {an_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[0]}]

set_property PACKAGE_PIN U4 [get_ports {an_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[1]}]

set_property PACKAGE_PIN V4 [get_ports {an_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[2]}]

set_property PACKAGE_PIN W4 [get_ports {an_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_sel[3]}]

